GET http://localhost:3100/

###
# @name createUser
POST http://localhost:3100/user
Content-Type: application/json

{
  "email": "teste@t2.com",
  "password": "12345678"
}

###
# @name login
POST http://localhost:3100/auth/login
Content-Type: application/json

{
  "email": "teste@t2.com",
  "password": "12345678"
}

GET http://localhost:3100/perfil
Authorization: Bearer {{login.response.body.token}}